### ISSUE TITLE
Uncaught ReferenceError: production is not defined

### ISSUE THREAD

**Issue by nostyleguy** [roundupapp/vue-plaid-link#1]
I am using the webpack Vue 2.0 project template. 

Steps:
* I ran 'npm install vue-plaid-link --save' 
* created a 1-page component with the sample code in the README. 
* I use vue-router to route directly to the component, which works if I remove the vue-plaid stuff
* run 'npm run dev'

I get:

"Uncaught ReferenceError: production is not defined" coming from ../node_modules/vue-plaid-link/dist/index.js

This is very possible user error. I am new to the Vue ecosystem and the webpack template even more so, but I am lost at how to resolve this. 

Thanks

**Comment by pushchris** [comment]
@nostyleguy thanks for sending this in! Looks like there was an issue in the webpack template that was causing this behavior. Could you give it another try now and let me know if you are still seeing the issue?

**Comment by nostyleguy** [comment]
That did the trick! It's working as expected now.

Thanks for the quick response!
