### ISSUE TITLE
Style Not Loading

### ISSUE THREAD

**Issue by tonyf** [roundupapp/vue-plaid-link#2]
Plaid Link Button CSS isn't being applied to the component

**Comment by pushchris** [comment]
@tonyf can you give me a little more detail on what you are referring to? Are you trying to apply your own style that isn't going through or are you referring to the way the button looks in the Plaid Link Demo?

**Comment by tonyf** [comment]
@pushchris This is a mistake on my end actually. I was thinking that the way the button looks in the demo is a style that they enforce with the API. But, turns out that's not the case.
