### ISSUE TITLE
Update to latest params

### ISSUE THREAD

**Issue by someone1** [roundupapp/vue-plaid-link#6]
https://plaid.com/docs/#parameter-reference

The following are missing or not accurately typed:

- `product` should be of type `String[]`
- `onLoad` should be added
- `language` should be added
- `countryCodes` should be added as type `String[]`
- optionally add `isWebView` as well

**Comment by pushchris** [comment]
@someone1 sorry for the delay in getting back to you! Appreciate you bringing these new keys to my attention, I have added them in and updated the package
